#!/usr/bin/env Rscript
# =============================================================================
# wri_extent.R - Generate wri_extent package data object
#
# Purpose:
#   Create a data object containing the spatial extent and properties of
#   WRI COG layers. This is used for fast validation without loading STAC.
#
# About data-raw/:
#   The data-raw/ directory contains scripts that generate package data objects.
#   These scripts are NOT included in the installed package - only the resulting
#   .rda files in data/ are included. This keeps the package size small while
#   documenting how data objects were created.
#
#   Reference: R Packages (2e), Chapter 7 - Data
#   https://r-pkgs.org/data.html#sec-data-data-raw
#
# Usage:
#   source("data-raw/wri_extent.R")
#
# Output:
#   data/wri_extent.rda (R data file used by the package)
#
# =============================================================================

library(terra)

# -----------------------------------------------------------------------------
# WRI Data Extent
# -----------------------------------------------------------------------------
# All WRI layers have consistent spatial properties:
#   - Native CRS: EPSG:5070 (Albers Equal Area Conic)
#   - Resolution: 90m x 90m
#   - Coverage: Western US, BC, Yukon
#
# These values come from the metadata CSV generated by wri-data-processing

# Extent in native CRS (EPSG:5070 Albers Equal Area)
# Units are meters
# Store as numeric vector (terra::SpatExtent objects don't serialize well)
epsg_5070_vec <- c(
  xmin = -5216639.67,
  xmax = -504689.67,
  ymin = 991231.69,
  ymax = 6199081.69
)

# Approximate extent in WGS84 (EPSG:4326)
# Used for human-readable error messages
# Note: Actual transformed extent is complex polygon due to projection
epsg_4326_vec <- c(
  xmin = -170.0,
  xmax = -50.0,
  ymin = 32.0,
  ymax = 72.0
)

# Resolution in meters (native CRS)
resolution <- c(x = 90, y = 90)

# Raster dimensions (columns x rows)
dimensions <- c(ncol = 52355, nrow = 57865)

# Create the data object
# Store extents as numeric vectors (will be converted to terra::ext() on use)
wri_extent <- list(
  epsg_5070 = epsg_5070_vec,
  epsg_4326 = epsg_4326_vec,
  resolution = resolution,
  dimensions = dimensions
)

# Save to data/ directory
# This will be loaded automatically when the package is loaded
usethis::use_data(wri_extent, overwrite = TRUE)

cat("✓ Generated data/wri_extent.rda\n")
cat("\nContents:\n")
print(wri_extent)