# =============================================================================
# data.R - Documentation for package data objects
#
# Purpose:
#   Document data objects that ship with the fedex package. This file uses
#   roxygen2 syntax to generate help pages for data objects.
#
# Reference: R Packages (2e), Chapter 7 - Documenting datasets
# https://r-pkgs.org/data.html#sec-documenting-data
# =============================================================================

#' WRI Data Extent and Properties
#'
#' Spatial extent and properties of the Wildfire Resilience Index (WRI)
#' Cloud Optimized GeoTIFF (COG) layers. All WRI layers share these
#' consistent spatial properties. This data object enables fast validation
#' of user-provided bounding boxes and shapefiles without loading the full
#' STAC catalog.
#'
#' @format A list with 4 elements:
#' \describe{
#'   \item{epsg_5070}{terra::SpatExtent object in EPSG:5070 (Albers Equal Area
#'     Conic, NAD83). Native CRS for WRI layers. Units are meters.
#'     Extent: xmin=-5216639.67, xmax=-504689.67, ymin=991231.69, ymax=6199081.69}
#'   \item{epsg_4326}{terra::SpatExtent object in EPSG:4326 (WGS84).
#'     Approximate extent in latitude/longitude for human-readable messages.
#'     Note: This is a simplified bounding box; actual transformed extent is
#'     an irregular polygon due to projection distortion.}
#'   \item{resolution}{Named numeric vector c(x=90, y=90). Native resolution
#'     in meters (EPSG:5070).}
#'   \item{dimensions}{Named numeric vector c(ncol=52355, nrow=57865). Full
#'     raster dimensions in pixels.}
#' }
#'
#' @details
#' All WRI COG layers have identical spatial properties:
#' \itemize{
#'   \item Native CRS: EPSG:5070 (Albers Equal Area Conic, NAD83)
#'   \item Resolution: 90 meters (both x and y)
#'   \item Coverage: Western United States, British Columbia, and Yukon
#'   \item Dimensions: 52,355 columns × 57,865 rows (3.0 billion pixels)
#' }
#'
#' These properties were extracted from the WRI metadata CSV generated by
#' the wri-data-processing pipeline and are guaranteed to be consistent
#' across all layers.
#'
#' @section Usage:
#' This data object is used internally by \code{\link{get_layer}} and
#' related functions to validate spatial inputs. You can also use it
#' directly for reference:
#'
#' \preformatted{
#' # Check WRI extent in different CRS
#' wri_extent$epsg_5070  # Native CRS
#' wri_extent$epsg_4326  # Lat/Lon (approximate)
#'
#' # Check resolution
#' wri_extent$resolution  # 90m x 90m
#'
#' # Check full raster dimensions
#' wri_extent$dimensions  # 52,355 x 57,865 pixels
#' }
#'
#' @examples
#' # View WRI extent in native CRS (meters)
#' wri_extent$epsg_5070
#'
#' # View approximate extent in lat/lon
#' wri_extent$epsg_4326
#'
#' # Get resolution
#' wri_extent$resolution
#'
#' # Calculate total number of pixels
#' prod(wri_extent$dimensions)
#'
#' @source Generated from WRI metadata by \code{data-raw/wri_extent.R}
"wri_extent"